"""Packaged HTML/CSS/JS assets, and the page shell every HTML artifact shares."""

from __future__ import annotations

import html
import json
from collections.abc import Sequence
from functools import lru_cache
from importlib.resources import files
from typing import Any

import altair as alt

from .. import PROJECT_URL

_ASSET_PACKAGE = "tembench.reporting.assets"

# Runs before the first paint, so a dark-mode reader never sees a white flash.
# A stored choice wins; otherwise the page follows the operating system.
_THEME_INIT = (
    "<script>(function(){var t;try{t=localStorage.getItem('tempobench-theme')}"
    "catch(e){}if(t!=='light'&&t!=='dark'){t=window.matchMedia&&"
    "matchMedia('(prefers-color-scheme: dark)').matches?'dark':'light'}"
    "document.documentElement.setAttribute('data-theme',t)})();</script>"
)

_SUN = (
    '<svg viewBox="0 0 24 24" width="16" height="16" aria-hidden="true" class="icon-sun">'
    '<circle cx="12" cy="12" r="4.5" fill="none" stroke="currentColor" stroke-width="2"/>'
    '<path d="M12 2v2.5M12 19.5V22M2 12h2.5M19.5 12H22M4.9 4.9l1.8 1.8M17.3 17.3l1.8 1.8'
    'M4.9 19.1l1.8-1.8M17.3 6.7l1.8-1.8" stroke="currentColor" stroke-width="2" '
    'stroke-linecap="round"/></svg>'
)
_MOON = (
    '<svg viewBox="0 0 24 24" width="16" height="16" aria-hidden="true" class="icon-moon">'
    '<path d="M20 14.5A8 8 0 1 1 9.5 4a6.5 6.5 0 0 0 10.5 10.5z" fill="none" '
    'stroke="currentColor" stroke-width="2" stroke-linejoin="round"/></svg>'
)
_THEME_TOGGLE = (
    '<button class="theme-toggle" id="themeToggle" type="button" '
    'aria-label="Switch between light and dark theme">'
    f'{_MOON}{_SUN}<span id="themeLabel">Dark</span></button>'
)


@lru_cache(maxsize=None)
def _asset(name: str) -> str:
    return files(_ASSET_PACKAGE).joinpath(name).read_text(encoding="utf-8")


def load_report_css() -> str:
    return _asset("report.css")


def vega_script_tags(indent: str = "  ") -> str:
    """CDN script tags for the Vega libraries matching the installed Altair.

    Altair writes specs against its own Vega-Lite schema; loading an older
    major version to render them drops or misreads newer properties.
    """
    # Altair 5 and 6 both export these; the fallbacks are Altair 5's values.
    vega = getattr(alt, "VEGA_VERSION", "5")
    vega_lite = getattr(alt, "VEGALITE_VERSION", alt.SCHEMA_VERSION.lstrip("v"))
    embed = getattr(alt, "VEGAEMBED_VERSION", "6")
    return "\n".join(
        f'{indent}<script src="https://cdn.jsdelivr.net/npm/{name}@{version}"></script>'
        for name, version in (
            ("vega", vega),
            ("vega-lite", vega_lite),
            ("vega-embed", embed),
        )
    )


def json_for_script(text: str) -> str:
    """Make JSON text safe to place inside an HTML ``<script>`` element.

    Chart data carries user-defined names: a literal ``</script>`` in one
    would end the element and run whatever follows.  The escapes are still
    the same JSON, since ``<``, ``>`` and ``&`` only occur inside strings.
    """
    return text.replace("<", "\\u003c").replace(">", "\\u003e").replace("&", "\\u0026")


def chart_slot(index: int, wide: bool = False) -> str:
    """Placeholder the page script renders chart `index` into.

    A `wide` chart has a fixed width (a faceted or stacked one cannot follow
    its container), so it scrolls sideways on a narrow screen instead.
    """
    cls = "chart chart-wide" if wide else "chart"
    return f'<div class="{cls}" id="chart-{index}"></div>'


def render_page(
    *,
    title: str,
    kind: str,
    body: str,
    meta: str = "",
    specs: Sequence[dict[str, Any]] = (),
    footer: str = "",
) -> str:
    """A complete HTML page in the shared TempoBench look.

    `title` is plain text; `meta`, `body` and `footer` are HTML the caller has
    already escaped.  Each of `specs` is a Vega-Lite spec rendered into the
    matching `chart_slot`, restyled whenever the reader switches theme.
    """
    from ..plotting._common import DARK_CONFIG  # charts import this module

    esc = html.escape
    charts = ""
    if specs:
        charts = "\n".join(
            [
                vega_script_tags(),
                '  <script type="application/json" id="tb-chart-specs">'
                f"{json_for_script(json.dumps(list(specs)))}</script>",
                '  <script type="application/json" id="tb-chart-dark">'
                f"{json_for_script(json.dumps(DARK_CONFIG))}</script>",
                f"  <script>\n{_asset('charts.js')}\n  </script>",
            ]
        )
    footer_html = footer or f'Generated by <a href="{PROJECT_URL}">TempoBench</a>'
    return f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="color-scheme" content="light dark">
  <title>{esc(title)}</title>
  {_THEME_INIT}
  <style>{load_report_css()}</style>
</head>
<body>
  <div class="container">
    <header class="page-header">
      <div class="page-heading">
        <div class="eyebrow">TempoBench · {esc(kind)}</div>
        <h1>{esc(title)}</h1>
        {f'<div class="meta">{meta}</div>' if meta else ''}
      </div>
      {_THEME_TOGGLE}
    </header>
    <main>
{body}
    </main>
    <footer class="page-footer">{footer_html}</footer>
  </div>
{charts}
  <script>
{_asset('theme-toggle.js')}
  </script>
</body>
</html>
"""
